"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: SpeedModule
  IDL file: SpeedData.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import SpeedModule


@dataclass
@annotate.final
@annotate.autoid("sequential")
class SpeedData(idl.IdlStruct, typename="SpeedModule.SpeedData"):
    speed: types.float64


